import React from "react";
import "../index.css";

function Privacy() {
  return (
    <>
      <>
  <div className="md:w-1/2 flex-col gap-10 my-10 font-custom">
    <h1 className="font-black text-3xl">Privacy Policy</h1>
    <p className="text-stone-700">
      Epash (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Epash.
      This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, Epash. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
    </p>

    <h2 className="font-bold text-2xl mt-6">Definitions and Key Terms</h2>
    <p className="text-stone-700">
      To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:
    </p>
    <ul className="list-disc list-inside text-stone-700">
      <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
      <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to SIA Epash, (Titurgas iela 6-38, Baloži, Latvia), that is responsible for your information under this Privacy Policy.</li>
      <li><strong>Country:</strong> where Epash or the owners/founders of Epash are based, in this case is Latvia.</li>
      <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Epash Service to manage the relationships with your consumers or service users.</li>
      <li><strong>Device:</strong> any internet-connected device such as a phone, tablet, computer or any other device that can be used to visit Epash and use the services.</li>
      <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet Protocol (IP) address, which can be used to identify the location from which a device is connecting to the Internet.</li>
      <li><strong>Personnel:</strong> refers to those individuals who are employed by Epash or are under contract to perform a service on behalf of one of the parties.</li>
      <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
      <li><strong>Service:</strong> refers to the service provided by Epash as described in the relative terms (if available) and on this platform.</li>
      <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
      <li><strong>Website:</strong> Epash’s site, which can be accessed via this URL: <a href="https://www.epashai.com/" className="text-blue-500">https://www.epashai.com/</a>.</li>
      <li><strong>You:</strong> a person or entity that is registered with Epash to use the Services.</li>
    </ul>

    <h2 className="font-bold text-2xl mt-6">What Information Do We Collect?</h2>
    <p className="text-stone-700">
      We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
    </p>
    <ul className="list-disc list-inside text-stone-700">
      <li>Name / Username</li>
      <li>Phone Numbers</li>
      <li>Email Addresses</li>
      <li>Job Titles</li>
      <li>Billing Addresses</li>
      <li>Debit/credit card numbers</li>
      <li>Age</li>
      <li>Password</li>
    </ul>

    <h2 className="font-bold text-2xl mt-6">When Does Epash Use End User Information from Third Parties?</h2>
    <p className="text-stone-700">
      Epash will collect End User Data necessary to provide the Epash services to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated.
    </p>

    <h2 className="font-bold text-2xl mt-6">Do We Share the Information We Collect with Third Parties?</h2>
    <p className="text-stone-700">
      We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
    </p>

    <h2 className="font-bold text-2xl mt-6">How Do We Protect Your Information?</h2>
    <p className="text-stone-700">
      We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information.
    </p>

    <h2 className="font-bold text-2xl mt-6">Your Consent</h2>
    <p className="text-stone-700">
      By using Epash or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services.
    </p>

    <h2 className="font-bold text-2xl mt-6">Contact Us</h2>
    <p className="text-stone-700">
      If you have any questions, you can reach us via email at <a href="mailto:support@epashai.com" className="text-blue-500">support@epashai.com</a> or visit our <a href="https://www.epashai.com/support" className="text-blue-500">Support Page</a>.
    </p>
  </div>
</>

    </>
  );
}

export default Privacy;
